SELECT AIRLINENAME FROM AIRLINE;

SELECT AIRLINECODE FROM AIRLINE;

SELECT * FROM AIRPORT;


SELECT P.PILOTLICENSE, PE.NAME FROM PILOT P, EMPLOYEE E, PERSON PE 
WHERE P.EMPLOYEENUMBER = E.EMPLOYEENUMBER AND E.IDPERSON = PE.IDPERSON 
AND P.AIRLINECODE = 'AV';

SELECT COUNT(*) FROM FLIGHT WHERE AIRLINECODE LIKE 'AV';

SELECT F.* FROM FLIGHT F WHERE F.AIRLINECODE LIKE 'AV';

SELECT FS.*, A.AIRPORTNAME FROM FLIGHTSEGMENT FS, FLIGHT F, AIRPORT A 
WHERE FS.AIRLINECODE = F.AIRLINECODE AND FS.FLIGHTNUMBER = F.FLIGHTNUMBER 
AND F.AIRLINECODE LIKE 'AV' AND F.FLIGHTNUMBER = '6' 
AND FS.ARR_AIRPORTCODE = A.AIRPORTCODE;

/*NUM SEGMENTOS*/
SELECT COUNT(*) FROM FLIGHTSEGMENT FS, FLIGHT F, AIRPORT A 
WHERE FS.AIRLINECODE = F.AIRLINECODE AND FS.FLIGHTNUMBER = F.FLIGHTNUMBER 
AND F.AIRLINECODE LIKE 'DL' AND F.FLIGHTNUMBER = '3' 
AND FS.DEP_AIRPORTCODE = A.AIRPORTCODE;

/*AEROPUERTO*/
SELECT A.AIRPORTNAME FROM FLIGHTSEGMENT FS, FLIGHT F, AIRPORT A 
WHERE FS.AIRLINECODE = F.AIRLINECODE AND FS.FLIGHTNUMBER = F.FLIGHTNUMBER 
AND F.AIRLINECODE LIKE 'AV' AND F.FLIGHTNUMBER = '6' 
AND FS.DEP_AIRPORTCODE = A.AIRPORTCODE AND ROWNUM <= 1;

/*PILOTO*/
SELECT PE.NAME FROM PILOT P, EMPLOYEE E, PERSON PE, PILOTASSIGNMENT PA 
WHERE P.EMPLOYEENUMBER = E.EMPLOYEENUMBER AND E.IDPERSON = PE.IDPERSON
AND PA.PILOTLICENSE = P.PILOTLICENSE AND PA.AIRLINECODE = 'AV' 
AND PA.FLIGHTNUMBER = '6' AND ROWNUM <= 1;

/*NUEVO VUELO*/
SELECT AL.AIRLINENAME, FL.FLIGHTNUMBER, (SELECT COUNT(*) FROM FLIGHTSEGMENT FS, FLIGHT F, AIRPORT A 
WHERE FS.AIRLINECODE = F.AIRLINECODE AND FS.FLIGHTNUMBER = F.FLIGHTNUMBER 
AND F.AIRLINECODE LIKE 'DL' AND F.FLIGHTNUMBER = '5' 
AND FS.DEP_AIRPORTCODE = A.AIRPORTCODE) NUM, (SELECT A.AIRPORTNAME FROM FLIGHTSEGMENT FS, FLIGHT F, AIRPORT A 
WHERE FS.AIRLINECODE = F.AIRLINECODE AND FS.FLIGHTNUMBER = F.FLIGHTNUMBER 
AND F.AIRLINECODE LIKE 'DL' AND F.FLIGHTNUMBER = '5' 
AND FS.DEP_AIRPORTCODE = A.AIRPORTCODE AND ROWNUM <= 1) NAME, (SELECT PE.NAME FROM PILOT P, EMPLOYEE E, PERSON PE, PILOTASSIGNMENT PA 
WHERE P.EMPLOYEENUMBER = E.EMPLOYEENUMBER AND E.IDPERSON = PE.IDPERSON
AND PA.PILOTLICENSE = P.PILOTLICENSE AND PA.AIRLINECODE = 'DL' 
AND PA.FLIGHTNUMBER = '5' AND ROWNUM <= 1) PILOT
FROM  AIRLINE AL, FLIGHT FL WHERE AL.AIRLINECODE = FL.AIRLINECODE AND
FL.AIRLINECODE = 'DL' AND FL.FLIGHTNUMBER = '5';

/*INFO SEGMENTOS*/
/*SEGMENTOS*/
SELECT FS.AIRLINECODE ||''|| FS.FLIGHTNUMBER VUELO, AL.AIRLINENAME AEROLINEA, 
FS.DEP_AIRPORTCODE, FS.ARR_AIRPORTCODE, (SELECT PE.NAME FROM PILOT P, EMPLOYEE E, PERSON PE, PILOTASSIGNMENT PA 
WHERE P.EMPLOYEENUMBER = E.EMPLOYEENUMBER AND E.IDPERSON = PE.IDPERSON
AND PA.PILOTLICENSE = P.PILOTLICENSE AND PA.AIRLINECODE = 'DL' 
AND PA.FLIGHTNUMBER = '5' AND ROWNUM <= 1) PILOTO FROM FLIGHTSEGMENT FS, AIRLINE AL, 
FLIGHT F WHERE AL.AIRLINECODE = FS.AIRLINECODE 
AND FS.AIRLINECODE = F.AIRLINECODE AND FS.FLIGHTNUMBER = F.FLIGHTNUMBER
AND FS.FLIGHTNUMBER = '5' AND FS.AIRLINECODE LIKE 'DL';

/*DATOS CIUDAD*/
SELECT P1.PLACENAME PAIS, PT.DESPLACETYPE TIPO,P2.PLACENAME DIVISION, 
P3.PLACENAME CIUDAD, A.AIRPORTNAME AEROPUERTO FROM PLACE P1, PLACE P2, PLACE P3, 
PLACETYPE PT, AIRPORT A WHERE P3.IDPLACE = A.IDPLACE 
AND P3.PLA_IDPLACE = P2.IDPLACE AND P2.PLA_IDPLACE = P1.IDPLACE 
AND PT.IDPLACETYPE = P2.IDPLACETYPE AND A.AIRPORTCODE LIKE 'BAQ';

/*CONEXIÓN*/
SELECT AL.AIRLINENAME AEROLINEA, FC.DEP_FLIGHTNUMBER NUM, 
AP.AIRPORTNAME AIRPORT FROM FLIGHTCONNECTION FC, AIRPORT AP, AIRLINE AL 
WHERE FC.ARR_AIRPORTCODE = AP.AIRPORTCODE AND FC.DEP_AIRLINECODE = AL.AIRLINECODE
AND FC.ARR_FLIGHTNUMBER = '2' AND FC.ARR_AIRLINECODE LIKE 'AC';


/*REPORTE*/
/*DIRECTO*/
SELECT FS.AIRLINECODE, FS.FLIGHTNUMBER
FROM FLIGHTSEGMENT FS WHERE FS.ARR_AIRPORTCODE = 'MDE' 
OR FS.DEP_AIRPORTCODE = 'RCH' GROUP BY FS.AIRLINECODE, FS.FLIGHTNUMBER
HAVING COUNT(*)>=2;

/*CONEXIÓN*/
SELECT * FROM FLIGHTSEGMENT FS, FLIGHTCONNECTION FC 
WHERE FS.ARR_AIRPORTCODE = 'ACA' AND FC.DEP_AIRLINECODE = FS.AIRLINECODE 
AND FC.DEP_FLIGHTNUMBER = FS.FLIGHTNUMBER;

/*BUSCAR DEPARTURE*/
SELECT * FROM FLIGHTSEGMENT FS WHERE (FS.DEP_AIRPORTCODE = 'MDE'
OR FS.ARR_AIRPORTCODE = 'MDE') AND FS.FLIGHTNUMBER = '1' 
AND FS.AIRLINECODE LIKE 'AM';

